#!/bin/bash

set -eu

SCRIPT_DIR=$(dirname "$(realpath "$0")")

DEFAULT_THALI_ROOT=$(realpath "$SCRIPT_DIR/../Thali_CordovaPlugin")
THALI_ROOT=$(realpath "${1:-$DEFAULT_THALI_ROOT}")

BTLIB_VERSION="0.3.9"
JXCORE_CORDOVA_VERSION="0.1.10"
JXCORE_CORDOVA_URL="http://jxcore.azureedge.net/jxcore-cordova/0.1.10/release/io.jxcore.node.jx"

echo 'Setting up server...'
(
  cd "${SCRIPT_DIR}/server"
  npm install
)
echo 'Done'


echo 'Setting up cordova app...'
(
  cd "${SCRIPT_DIR}/install"
  npm install
)

(
  cd "${SCRIPT_DIR}/www/jxcore"
  npm install --no-optional
)

(
  cd "${SCRIPT_DIR}"
  echo "Installing jxcore-cordova@${JXCORE_CORDOVA_VERSION}"
  mkdir -p thaliDontCheckIn/localdev
  install/node_modules/.bin/jxc install \
    "$JXCORE_CORDOVA_VERSION" \
    --use-url "$JXCORE_CORDOVA_URL"

  echo "Adding thali cordova plugin"
  cordova plugin add "${THALI_ROOT}"

  echo "Updating thali cordova plugin's gradle.properties file"
  cat <<GRADLEPROPERTIES > plugins/org.thaliproject.p2p/src/android/gradle.properties
btconnectorlib2Version = ${BTLIB_VERSION}
cdvMinSdkVersion = 21
cdvCompileSdkVersion = android-23
GRADLEPROPERTIES
)


echo 'Done'

cat <<\INFO

To build app for android run

    cordova platform add andoird
    cordova build android --device --release

For iOS build replace `andoird' with `ios'

INFO
